### ISSUE TITLE
Upgrade to truffle 5 causes migration to fail with "error while converting number null to BN.js"

### ISSUE THREAD

**Issue by lakamsani** [trufflesuite/truffle#1392]
- [x ] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.
- Tried the workaround suggest in that Gitter channel and also after talking to @gnidan just now at [Devcon4](https://devcon4.ethereum.org) but not having luck. Tried [right after](https://github.com/PulseBlockchain/oz-sample-app/blob/ed52f82b5d0a504adf4950f3e975f90d2be5cdbc/test/TestCrowdsale.js#L24) `require` statements for the artifacts as well as in the `before` [function](https://github.com/PulseBlockchain/oz-sample-app/blob/ed52f82b5d0a504adf4950f3e975f90d2be5cdbc/test/TestCrowdsale.js#L46). 
---------------------------

## Issue

I have 18 mocha truffle/mocha tests that all pass with truffle4 but migration fails in truffle5. 

## Steps to Reproduce
Please check out this sample repo branch https://github.com/PulseBlockchain/oz-sample-app/tree/vamsee/truffl5-oz-2  and run `truffle test` with the latest truffle5. 

## Expected Behavior

All tests should pass as before with truffle4
 
## Actual Results

What actually happened. Please give examples and support it with screenshots, copied output or error messages.

```
truffle5 test
Using network 'development'.

Error: while migrating TestCrowdsale: Error: [number-to-bn] while converting number null to BN.js instance, error: invalid number value. Value must be an integer, hex string, BN or BigNumber instance. Note, decimals are not supported. Given value: "NaN"
    at /Users/vamsee/Development/blockchain/trufflesuite/truffle-via-npm/node_modules/truffle/build/webpack:/packages/truffle-deployer/src/deployment.js:359:1
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
Truffle v5.0.0-next.14 (core: 5.0.0-beta.1)
Solidity v0.4.25 (solc-js)
Node v8.10.0
```

## Environment

* Operating System: macOS mojave
* npm 5.6.0

**Comment by lakamsani** [comment]
BTW, I have truffle4 installed globally and truffle5 installed separately so I can try both quickly without another `npm install -g`. That is the reason for `truffle5` command above. Perhaps there is a way to have multiple versions globally.

**Comment by fainashalts** [comment]
Hi @lakamsani, thanks for reaching out about this. I cloned your repo to see what I could do to help. There appear to be a few things going on here so I hope you don't mind but I'll walk you through what I was able to address: 

First, you should make sure that you are actually connected to web3. I didn't see a requires in the 2_Test-Crowdsale.js file, and when I added it I was able to get the latest block times, which were returning null before and throwing this error. I just required it locally to test with ganache-cli, but of course you can connect it to whatever blockchain you are using. 

Second, I got an error about bignumber being missing, so I installed it and required it as well. I needed to convert cap eth and goal eth in 2_Test-Crowdsale.js  to big numbers in order for them to be accepted by the deployment function.

Unfortunately, once this was resolved, I got the following error: 

Error: while migrating TestCrowdsale: Returned error: VM Exception while processing transaction: revert
    at /Users/fainashalts/truffle-dev/truffle/packages/truffle-deployer/src/deployment.js:363:17
    at process.internalTickCallback (internal/process/next_tick.js:77:7)

I have a hunch this is similar to what was going in this issue, so you may want to pursue a similar solution: https://github.com/trufflesuite/truffle/issues/884

Also, I am seeing a test failure for Contract: ICO Signature and Platform Tests that TypeError: web3.currentProvider.sendAsync is not a function

You may need to do something different since Truffle5 uses the newest version of Web3, so check out the docs: https://web3js.readthedocs.io/en/1.0/web3-eth.html#currentprovider

If that doesn't help, you may want to try the solution here: https://github.com/ethjs/ethjs/issues/6

I hope some of this is helpful, and if you continue to have a problem with the specific error here after following these steps, please feel free to reopen this issue with more information. Thanks and I hope you're having a great time at DevCon4!

**Comment by lakamsani** [comment]
@fainashalts  thanks for looking into this providing detailed feedback. Given that all my tests were working with Truffle4, looks somehow `web3` instance was being magically injected by Truffle4 but not anymore. If you could send a PR with all your changes or simply paste the changes you made in `2_Test-Crowdsale.js` that would be great. I can pick up from there and figure out the other issues.  I fixed that signature test problem in my main project repo (this repo is a small slice of my main project and I used to reproduce issues etc).

**Comment by fainashalts** [comment]
Hi @lakamsani, happy to help. I don't have the code anymore as I was just digging around to see if this is an issue with Truffle v5 that needs addressing in our code. The steps above should get you most of the way there though!

You are right, I believe web3 was previously being globally required and now needs to be required explicitly. Also, I forgot to mention in my previous comment that the `web3.eth.getBlock('latest')` api call returns a promise, so you'll need to wrap it in an async/await to ensure you can get that value.

Here is a link to the release notes for this version of Truffle, with loads of information on different features that have been added: https://github.com/trufflesuite/truffle/releases

**Comment by lakamsani** [comment]
@fainashalts  I just pushed a commit to my branch where I tried some of your instructions. I do see a change in behavior but now it stopping with a different error as shown below. So I 'm not able to get to the point where you were. Can you send me a sample project that shows the correct way to initialize web3 in Truffle5 now that it is not being injected anymore? 

You can see in my latest commit that I had to initalize web3 in two different places hard-coding the host/port. 
* First in migration script. https://github.com/PulseBlockchain/oz-sample-app/blob/1c6fe23db4aeae7c255dbd4aef7ec9f1b71023be/migrations/2_Test-Crowdsale.js#L7
* Again in the test itself. https://github.com/PulseBlockchain/oz-sample-app/blob/1c6fe23db4aeae7c255dbd4aef7ec9f1b71023be/test/TestCrowdsale.js#L9

Is there anyway to make my deployment code use the same web3 url as passed to the `truffle test --network` argument where it picks up from  `truffle-config.js` . For example it picks up the default `development` if you omit the `--network` parameter to `truffle test` whose url is `http://localhost:8545`

```
[Function: sass]
TypeError: Cannot read property 'getBlock' of undefined
    at module.exports (/Users/vamsee/Development/blockchain/pulse/oz-sample-app/migrations/2_Test-Crowdsale.js:24:38)
    at Require.file (/Users/vamsee/Development/blockchain/trufflesuite/truffle-via-npm/node_modules/truffle/build/webpack:/packages/truffle-migrate/migration.js:59:1)
    at /Users/vamsee/Development/blockchain/trufflesuite/truffle-via-npm/node_modules/truffle/build/webpack:/packages/truffle-require/require.js:101:1
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:511:3)
Truffle v5.0.0-next.14 (core: 5.0.0-beta.1)
Solidity v0.4.25 (solc-js)
Node v8.10.0
```

**Comment by fainashalts** [comment]
Hi @lakamsani, unfortunately we don't have the bandwidth to troubleshoot questions that are not directly related to issues/bugs in Truffle's codebase. The error you posted is likely due to web3 still not being connected as you have it written, also you should make sure you have a blockchain running on 8545 if that is what you're using to connect web3. 

Gitter is a great place to ask for help with questions that are more specific to your own code, I highly recommend it! https://gitter.im/ConsenSys/truffle

**Comment by lakamsani** [comment]
@fainashalts this is serious DX (developer experience) problem. Gitter is completely useless as far as getting support is concerned. Questions get lost if no one answers them in time. If the truffle team is really serious about developer adoption you should provide a sample "hello world" type project (outside of the truffle boxes) that shows how to initialize web3 in truffle5 as it has changed quite a bit from how it is done in truffl4. Otherwise, developers will start looking for alternatives like https://github.com/nomiclabs/buidler. It's kind of odd that you are not able to provide the code changes you have already made that let's this project get past the web3 initialization issues!

**Comment by lakamsani** [comment]
@fainashalts  I had an incorrect import for the nee web3 in the migrations script. After I fixed that getting this error which I believe you fixed before in your local test. From the truffle error message, it is not clear what line of the migration script is problematic. Is there some way to find that?

```
   Deploying 'TestCrowdsale'
   -------------------------
Deplyoment failed
Error:  *** Deployment Failed ***

"TestCrowdsale" -- Error: [number-to-bn] while converting number {"number":"Invalid Number","sign":1,"rest":0} to BN.js instance, error: invalid number value. Value must be an integer, hex string, BN or BigNumber instance. Note, decimals are not supported. Given value: "Invalid Number".

    at /Users/vamsee/Development/blockchain/trufflesuite/truffle-via-npm/node_modules/truffle/build/webpack:/packages/truffle-deployer/src/deployment.js:359:1
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
   > Saving artifacts
   -------------------------------------
   > Total cost:          0.02951162 ETH

```

**Comment by eggplantzzz** [comment]
I think version 1 of web3 uses the BN library and not BigNumber.  In your migration file you are doing `const BigNumber = Web3.BigNumber;` which for me on my local comes out as `undefined`.  I haven't scoured your code but try and resolve that issue and see what happens.
