### ISSUE TITLE
"Migrations" -- The contract code couldn't be stored, please check your gas limit..

### ISSUE THREAD

**Issue by gnorbsl** [trufflesuite/truffle#1575]
- [ X] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.

---------------------------

## Issue

Trying to deploy a contract to mainnet, once Truffle tries to deploy the migrations it fails with the message 

    "Migrations" -- The contract code couldn't be stored, please check your gas limit..

    at /home/patric/.npm-global/lib/node_modules/truffle/build/webpack:/packages/truffle-deployer/src/deployment.js:364:1
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)

My truffle.js settings:

         main: {
            gas: 8000000,
            provider: function() {
                return new HDWalletProvider('', "https://mainnet.infura.io/v3/apikey")
            },
            network_id: "*"
        },

 the contract gets mined successfully though

## Expected Behavior

Contract gets deployed successfully

## Actual Results

migrations fails

## Environment

* Operating System: Linux Mint
* Ethereum client: infura
Truffle v5.0.0-beta.2 (core: 5.0.0-beta.2)
Solidity v0.5.0 (solc-js)
Node v8.14.0
* npm version (`npm --version`): 6.4.1

**Comment by mrwillis** [comment]
I have the exact same issue - transaction is successful but truffle returns this error.

**Comment by mrwillis** [comment]
The best solution I have is to just split up the migrations into 1-2 transactions each and if one of them fails due to this error simply `truffle migrate --network main` again

**Comment by eggplantzzz** [comment]
@gnorbsl Sorry for the delay in responding to this! Are you still experiencing this issue? Have you tried adjusting your gasLimit etc?

**Comment by gnorbsl** [comment]
I don't quite remember, I think it was fixed after I switched to infura and
truffle 5. Sorry that I can't offer more details.

Am Do., 14. Feb. 2019, 16:49 hat tyler feickert <notifications@github.com>
geschrieben:

**Comment by eggplantzzz** [comment]
Toll, let us know if it happens again. Closing this for now.

**Comment by Arachnid** [comment]
I'm having this problem intermittently, and I'm fairly sure that the issue is that infura serves requests from a cluster of nodes; when a contract creation transaction is mined, it calls `eth_getCode`, and sometimes gets a response from a node that hasn't seen that new block yet.

A stopgap solution might be to try again after a short delay if getCode returns nothing, before giving up.

**Comment by gnidan** [comment]
That's a fantastic hypothesis @Arachnid!

Some quick implementation thoughts, for any takers: 

A [similar retry mechanism](https://github.com/trufflesuite/truffle/blob/develop/packages/contract/lib/override.js#L28-L37) already exists, to handle Web3.js's 50-block timeout (side note: does that limitation still exist?). 

Defining another "override" like that one seems viable and at low-risk of breaking any architecture. It should be easy to hack together, although it's a bit tricky to chase down how those overrides get hooked up.

(Another approach might be to do it in @truffle/deployer, but that seems strictly less useful?)

Anyway, sounds like this one's open again!

**Comment by gnidan** [comment]
Ah but @CruzMolina says `eth_getCode` might not happen inside @truffle/contract, so my implementation ideas may not hold. Further investigation required.

**Comment by CruzMolina** [comment]
#2257 appears to be the same issue.

**Comment by CruzMolina** [comment]
Reproduction steps [here](https://github.com/trufflesuite/truffle/issues/2257#issuecomment-558919818). Hopefully still working ( 🤞).

Potential solution [here](https://github.com/trufflesuite/truffle/issues/2257#issuecomment-565516714).
