### ISSUE TITLE
Make test runner's BEFORE_TIMEOUT configurable

### ISSUE THREAD

**Issue by tcoulter** [trufflesuite/truffle#261]
I've received some complaints that the pre-deploy steps aren't completing within 120s on some slow test nets. We should make this value configurable.

**Comment by chevdor** [comment]
That´s especially true when testing again real nets (vs testrpc).

**Comment by chevdor** [comment]
The fix in #267 allows specifying the timeouts per network.

For instance:
```
networks: {
        "morden": {
            network_id: 2,            
            host: "localhost",
            port: 8546,
            before_timeout: 200000,          //  <=== NEW
            test_timeout: 300000             //  <=== NEW
        },
        "dev": {
            network_id: "default",
            before_timeout: 300,             //  <=== NEW
            test_timeout: 300                //  <=== NEW
        }
    }
```

**Comment by PeterBorah** [comment]
Running into this issue.

**Comment by vkantchev** [comment]
@tcoulter This seems to have been fixed at some point and then the commit was reverted back. If you check the latest code in the `develop` branch of `truffle-core` in `/lib/test.js` the code still uses hardcoded timeouts.

**Comment by cgewecke** [comment]
@vkantchev You should be able to completely disable timeouts by setting a mocha key in the config as below: 

```javascript
module.exports = {
    networks: {
        development: {
            host: "localhost",
            port: 8545,
            network_id: "*",
        },
        .. etc ...
    },
    mocha: {
        enableTimeouts: false,
    }
}
```

**Comment by gnidan** [comment]
Looks like this issue can be closed. Thanks! (Feel free to holler at me to reopen)

**Comment by peterbroadhurst** [comment]
Hi @gnidan - I've just raised https://github.com/trufflesuite/truffle/pull/2008 as we're still seeing the timeout kick in with `enableTimeouts: false` set.
