### ISSUE TITLE
Error in installing truffle in macOS

### ISSUE THREAD

**Issue by rexdai** [trufflesuite/truffle#3270]
## Issue

I am facing some issue in the installation of truffle. I used the command

```
npm install -g truffle
npm WARN deprecated flat@4.1.0: Fixed a prototype pollution security issue in 4.1.0, please upgrade to ^4.1.1 or ^5.0.1.
/usr/local/bin/truffle -> /usr/local/lib/node_modules/truffle/build/cli.bundled.js

> truffle@5.1.40 postinstall /usr/local/lib/node_modules/truffle
> node ./scripts/postinstall.js

- Fetching solc version list from solc-bin. Attempt #1
+ truffle@5.1.40
added 123 packages from 68 contributors in 119.58s

```

However, my version is indeed v5.1.40
```
truffle version
Truffle v5.1.40 (core: 5.1.40)
Solidity v0.5.16 (solc-js)
Node v14.8.0
Web3.js v1.2.1
```

I'm new to Solidity and really don't know how to fix this. Please HELPPPPP!

* Operating System: Mac OS Mojave 10.14.6
* Ethereum client:
* Truffle version (`truffle version`):v5.1.40
* node version (`node --version`):v.14.8.0
* npm version (`npm --version`): 6.14.7

**Comment by valekar** [comment]
@rexdai Did I miss something in the above question ? what exactly is your issue ? One thing I always do is uninstall completely and then install truffle again if I face any issues

**Comment by rexdai** [comment]
> @rexdai Did I miss something in the above question ? what exactly is your issue ? One thing I always do is uninstall completely and then install truffle again if I face any issues

Hi, my problem is the "prototype pollution security issue" while installing",  ("WARN deprecated flat@4.1.0: Fixed a prototype pollution security issue in 4.1.0, please upgrade to ^4.1.1 or ^5.0.1.
/usr/local/bin/truffle -> /usr/local/lib/node_modules/truffle/build/cli.bundled.js
" ), but as I can tell, my truffle version is already 5.1.40.

I've tried to uninstall using both "npm uninstall -g truffle" and "sudo npm uninstall -g truffle", and reinstall, but neither worked.

**Comment by gnidan** [comment]
Hm, well firstly, Truffle doesn't support Node v14, but that doesn't appear to be the issue here.

How'd you install Node in the first place? Are you using NVM?

**Comment by rexdai** [comment]
@gnidan Hi, thanks so much for replying! The command I ran and received the "prototype pollution" output is exactly `npm install -g truffle`, please see attachment for more details.
<img width="1369" alt="屏幕快照 2020-08-19 下午3 55 09" src="https://user-images.githubusercontent.com/69676598/90612166-431a5080-e23a-11ea-93a2-c1856a80d994.png">

**Comment by gnidan** [comment]
Hm, but that's just a warning...

Something we should look at, but are you able to use Truffle? It looks like you could probably ignore that warning. For instance: if you do `truffle test`, does it run?

**Comment by gnidan** [comment]
We just dug in a bit, looks like `flat` is used by `truffle` via `mocha` via `yargs-unparser`. We recently did an upgrade of mocha, but we might need to look into this again.

(Noting this just for future investigation purposes; @rexdai you should still be fine, I think)

**Comment by victorleejw** [comment]
> I've been having the same sort of problems getting started, I assumed i was doing something wrong. Am I?
> ![Screen Shot 2020-08-21 at 10 57 40 AM](https://user-images.githubusercontent.com/68294677/90920729-aa9ce100-e39d-11ea-8946-30698e229826.png)

I had the same issue and its related to the MacOS security settings. I solved it by using sudo npm install truffle -g

**Comment by eggplantzzz** [comment]
I do not recommend using `sudo` to install Truffle. There are sometimes a lot of other permissions errors that pop up when installing Truffle this way.

I think the best solution is to use `npm` with a Node version manager such as `nvm` and this is what `npm` recommends. See [this article](https://docs.npmjs.com/resolving-eacces-permissions-errors-when-installing-packages-globally).

**Comment by rexdai** [comment]
> Hm, but that's just a warning...
> 
> Something we should look at, but are you able to use Truffle? It looks like you could probably ignore that warning. For instance: if you do `truffle test`, does it run?

@gnidan Thank you for your help! Unfortunately, `truffle test` does not work. The error is apparently affecting the installation process.
<img width="370" alt="屏幕快照 2020-08-31 下午10 46 03" src="https://user-images.githubusercontent.com/69676598/91733151-c85b1900-ebdb-11ea-92ae-4fdf0ac06e9b.png">

**Comment by eggplantzzz** [comment]
Also, I don't think Truffle is fully compatible with Node 14. Try downgrading to 12, re-installing, and seeing if it makes a difference.

**Comment by fainashalts** [comment]
@davidmurdoch just pinging you here so you can let the poster know when we have support for node v14!

**Comment by haltman-at** [comment]
OK, this should now be fixed with this week's release!   Please let us know if it's not.

**Comment by williamrobertbush** [comment]
Hi there, 

I am running into this issue right now. I was wondering what I need to do to get past this. I am following a tutorial to create a crypto swap app and the versions he uses are much older. I have found that v14 doesn't support truffle but you are saying this has been fixed as of Oct 2020. Please let me know.

**Comment by blakcinc** [comment]
I never resolved the issue

**Comment by williamrobertbush** [comment]
Bummer. My mac is ancient and I can't seem to figure out how to downgrade to v12.

**Comment by haltman-at** [comment]
@williamrobertbush OK, we can reopen this.  Can you be more specific about what you're seeing?

**Comment by williamrobertbush** [comment]
Truffle is not compatible with Node v14. I cannot run a 2nd migration contract inside truffle. Truffle just will not allow it from what I understand. @blakcinc said the issue was never resolved. When I run truffle migrate, my 2nd contract will not deploy.

**Comment by ValTulip** [comment]
Im having problems with installing Truffle. I tried everything... And still dont work.
![Screenshot 2021-03-27 at 22 27 16 copy](https://user-images.githubusercontent.com/81491561/112750017-49d62680-8fc6-11eb-97bc-2fa2ebc2178d.jpg)

**Comment by ValTulip** [comment]
Hello, I tried everything to run Truffle. What can I do? I tried with node-v14.16.0 and with node-v15.12.0. 
![Screenshot 2021-03-27 at 22 27 16 copy](https://user-images.githubusercontent.com/81491561/112750071-93bf0c80-8fc6-11eb-847b-e880771176b5.jpg)

**Comment by kashicookie** [comment]
<img width="1251" alt="Screen Shot 2021-04-01 at 9 29 56 PM" src="https://user-images.githubusercontent.com/81785260/113371030-45499f00-9333-11eb-84f7-156f77914464.png">

im running into the same issue. I am using a 2018 iMac running iOS Big Sur. Please advise. I am also going through similar course that others have mentioned

**Comment by eggplantzzz** [comment]
Truffle should have no problem running on Node 14. Once again, I don't recommend using `sudo` while installing Truffle. Use nvm with npm (as npm recommends) and you will avoid a lot of permissions errors. 

Check out [this article about using nvm](https://docs.npmjs.com/resolving-eacces-permissions-errors-when-installing-packages-globally) from npm.

**Comment by cds-amal** [comment]
Hi @rexdai, we're closing this for issue maintenance. Please comment if you'd like us to reopen. Thanks!

**Comment by kaideego** [comment]
has anyone been able to come to a solution for this? i even downloaded ### node v16.5.0 but it still had the ERR issues

**Comment by TommyVise** [comment]
i've fixed the problem with this command: **npm install -g npm**

**Comment by migueljulve** [comment]
hi, I got the same EACESS problem, I finally just used homebrew to install nvm, so npn and node, then use brew as well to install truffle, smooth as silk :)

**Comment by Raptoz** [comment]
@kashicookie check this 
https://docs.npmjs.com/resolving-eacces-permissions-errors-when-installing-packages-globally

**Comment by AhmadKarim72** [comment]
I have tried it with and without sudo but I still get the same thing. not sure what to do 

`ahmadkarim@Ahmads-MacBook-Pro ~ % sudo npm install truffle -g
npm WARN deprecated mkdirp-promise@5.0.1: This package is broken and no longer maintained. 'mkdirp' itself supports promises now, please switch to that.
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated ipld-raw@6.0.0: This module has been superseded by the multiformats module
npm WARN deprecated cids@1.1.9: This module has been superseded by the multiformats module
npm WARN deprecated uuid@2.0.1: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated multicodec@1.0.4: This module has been superseded by the multiformats module
npm WARN deprecated uuid@3.2.1: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated uuid@3.2.1: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated uuid@3.3.2: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated ipld-dag-cbor@0.17.1: This module has been superseded by @ipld/dag-cbor and multiformats
npm WARN deprecated multibase@4.0.6: This module has been superseded by the multiformats module
npm WARN deprecated multibase@4.0.6: This module has been superseded by the multiformats module
npm WARN deprecated multibase@4.0.6: This module has been superseded by the multiformats module
npm WARN deprecated multibase@3.1.2: This module has been superseded by the multiformats module
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated multibase@0.6.1: This module has been superseded by the multiformats module
npm WARN deprecated multibase@0.7.0: This module has been superseded by the multiformats module
npm WARN deprecated multicodec@0.5.7: This module has been superseded by the multiformats module
npm WARN deprecated ipld-dag-pb@0.20.0: This module has been superseded by @ipld/dag-pb and multiformats
npm WARN deprecated multicodec@3.2.1: This module has been superseded by the multiformats module
npm WARN deprecated node-pre-gyp@0.11.0: Please upgrade to @mapbox/node-pre-gyp: the non-scoped node-pre-gyp package is deprecated and only the @mapbox scoped package will recieve updates in the future
npm WARN deprecated multicodec@2.1.3: This module has been superseded by the multiformats module
npm WARN deprecated multicodec@2.1.3: This module has been superseded by the multiformats module
npm WARN deprecated multicodec@2.1.3: This module has been superseded by the multiformats module
npm WARN deprecated cids@0.7.5: This module has been superseded by the multiformats module
npm ERR! code 1
npm ERR! path /Users/ahmadkarim/.npm-packages/lib/node_modules/truffle/node_modules/ganache/node_modules/@trufflesuite/bigint-buffer
npm ERR! command failed
npm ERR! command sh -c node-gyp rebuild
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@9.0.0
npm ERR! gyp info using node@18.2.0 | darwin | arm64
npm ERR! gyp info find Python using Python version 3.9.7 found at "/Library/Frameworks/Python.framework/Versions/3.9/bin/python3"
npm ERR! gyp info spawn /Library/Frameworks/Python.framework/Versions/3.9/bin/python3
npm ERR! gyp info spawn args [
npm ERR! gyp info spawn args   '/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
npm ERR! gyp info spawn args   'binding.gyp',
npm ERR! gyp info spawn args   '-f',
npm ERR! gyp info spawn args   'make',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/Users/ahmadkarim/.npm-packages/lib/node_modules/truffle/node_modules/ganache/node_modules/@trufflesuite/bigint-buffer/build/config.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/usr/local/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/Users/ahmadkarim/Library/Caches/node-gyp/18.2.0/include/node/common.gypi',
npm ERR! gyp info spawn args   '-Dlibrary=shared_library',
npm ERR! gyp info spawn args   '-Dvisibility=default',
npm ERR! gyp info spawn args   '-Dnode_root_dir=/Users/ahmadkarim/Library/Caches/node-gyp/18.2.0',
npm ERR! gyp info spawn args   '-Dnode_gyp_dir=/usr/local/lib/node_modules/npm/node_modules/node-gyp',
npm ERR! gyp info spawn args   '-Dnode_lib_file=/Users/ahmadkarim/Library/Caches/node-gyp/18.2.0/<(target_arch)/node.lib',
npm ERR! gyp info spawn args   '-Dmodule_root_dir=/Users/ahmadkarim/.npm-packages/lib/node_modules/truffle/node_modules/ganache/node_modules/@trufflesuite/bigint-buffer',
npm ERR! gyp info spawn args   '-Dnode_engine=v8',
npm ERR! gyp info spawn args   '--depth=.',
npm ERR! gyp info spawn args   '--no-parallel',
npm ERR! gyp info spawn args   '--generator-output',
npm ERR! gyp info spawn args   'build',
npm ERR! gyp info spawn args   '-Goutput_dir=.'
npm ERR! gyp info spawn args ]
npm ERR! gyp info spawn make
npm ERR! gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
npm ERR! xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
npm ERR! gyp ERR! build error 
npm ERR! gyp ERR! stack Error: `make` failed with exit code: 1
npm ERR! gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:527:28)
npm ERR! gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:291:12)
npm ERR! gyp ERR! System Darwin 21.4.0
npm ERR! gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
npm ERR! gyp ERR! cwd /Users/ahmadkarim/.npm-packages/lib/node_modules/truffle/node_modules/ganache/node_modules/@trufflesuite/bigint-buffer
npm ERR! gyp ERR! node -v v18.2.0
npm ERR! gyp ERR! node-gyp -v v9.0.0
npm ERR! gyp ERR! not ok

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/ahmadkarim/.npm/_logs/2022-05-20T05_31_40_111Z-debug-0.log`

**Comment by AhmadKarim72** [comment]
![Screen Shot 2022-05-20 at 1 33 50 AM](https://user-images.githubusercontent.com/90279005/169457628-adeb607b-7b74-4457-803a-adb64988972c.png)

**Comment by Vishvesh-Codehunt** [comment]
hey i received the error like this while installing the trffule. What should i do to remove that error
<img width="1440" alt="Screen Shot 2022-07-10 at 4 06 28 PM" src="https://user-images.githubusercontent.com/75875506/178141321-b694c07d-8f44-42a8-8aeb-1e583404cfed.png">
?
