### ISSUE TITLE
Compile Error on apple M1 

### ISSUE THREAD

**Issue by UnsignedInt8** [trufflesuite/truffle#3804]
- [ ] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.

---------------------------

## Issue

Fatal error when compiling contracts on M1 MacBook 

## Steps to Reproduce

```
> truffle compile
```

## Expected Behavior

Compile contracts without errors

## Actual Results

```

✗ truffle compile

Compiling your contracts...
===========================


#
# Fatal error in , line 0
# Check failed: allocator->SetPermissions(reinterpret_cast<void*>(region.begin()), region.size(), PageAllocator::kNoAccess).
#
#
#
#FailureMessage Object: 0x16f385648
 1: 0x100b69044 node::NodePlatform::GetStackTracePrinter()::$_3::__invoke() [/opt/homebrew/bin/node]
 2: 0x1014f0fdc V8_Fatal(char const*, ...) [/opt/homebrew/bin/node]
 3: 0x1010da3b8 v8::internal::wasm::WasmCodeAllocator::GetNumCodeSpaces() const [/opt/homebrew/bin/node]
 4: 0x1010da258 v8::internal::wasm::WasmCodeAllocator::FreeCode(v8::internal::Vector<v8::internal::wasm::WasmCode* const>) [/opt/homebrew/bin/node]
 5: 0x1010dd0a8 v8::internal::wasm::NativeModule::FreeCode(v8::internal::Vector<v8::internal::wasm::WasmCode* const>) [/opt/homebrew/bin/node]
 6: 0x1010eac2c v8::internal::wasm::WasmEngine::FreeDeadCodeLocked(std::__1::unordered_map<v8::internal::wasm::NativeModule*, std::__1::vector<v8::internal::wasm::WasmCode*, std::__1::allocator<v8::internal::wasm::WasmCode*> >, std::__1::hash<v8::internal::wasm::NativeModule*>, std::__1::equal_to<v8::internal::wasm::NativeModule*>, std::__1::allocator<std::__1::pair<v8::internal::wasm::NativeModule* const, std::__1::vector<v8::internal::wasm::WasmCode*, std::__1::allocator<v8::internal::wasm::WasmCode*> > > > > const&) [/opt/homebrew/bin/node]
 7: 0x1010e8c4c v8::internal::wasm::WasmEngine::PotentiallyFinishCurrentGC() [/opt/homebrew/bin/node]
 8: 0x1010e9e88 v8::internal::wasm::WasmEngine::ReportLiveCodeForGC(v8::internal::Isolate*, v8::internal::Vector<v8::internal::wasm::WasmCode*>) [/opt/homebrew/bin/node]
 9: 0x1010ea178 v8::internal::wasm::WasmEngine::ReportLiveCodeFromStackForGC(v8::internal::Isolate*) [/opt/homebrew/bin/node]
10: 0x100d4df04 v8::internal::StackGuard::HandleInterrupts() [/opt/homebrew/bin/node]
11: 0x1010347a8 v8::internal::Runtime_WasmStackGuard(int, unsigned long*, v8::internal::Isolate*) [/opt/homebrew/bin/node]
12: 0x10125f7ec Builtins_CEntry_Return1_DontSaveFPRegs_ArgvOnStack_NoBuiltinExit [/opt/homebrew/bin/node]
13: 0x16104b6711b0 
14: 0x16104d7b4b20 
15: 0x16104ad20280 
16: 0x16104b5d4a1c 
17: 0x16104d31bf70 
18: 0x1e306abd3108 
19: 0x1011f84f4 Builtins_InterpreterEntryTrampoline [/opt/homebrew/bin/node]
20: 0x161049ae309c 
21: 0x16104e1c659c 
22: 0x16104d3192a4 
23: 0x1e306abcadd0 
24: 0x1011f84f4 Builtins_InterpreterEntryTrampoline [/opt/homebrew/bin/node]
25: 0x161049ae2dbc 
26: 0x16104e939bfc 
27: 0x16104d3192a4 
28: 0x1e306abcadd0 
29: 0x1011f84f4 Builtins_InterpreterEntryTrampoline [/opt/homebrew/bin/node]
30: 0x161049ae2dbc 
31: 0x16104e79afc0 
32: 0x16104d3193a4 
33: 0x1e306abcb060 
34: 0x1011f84f4 Builtins_InterpreterEntryTrampoline [/opt/homebrew/bin/node]
35: 0x161049ae2b9c 
36: 0x16104e6f37e0 
37: 0x16104d3192a4 
38: 0x1e306abcadd0 
39: 0x1011f84f4 Builtins_InterpreterEntryTrampoline [/opt/homebrew/bin/node]
40: 0x161049ae2dbc 
41: 0x16104e73518c 
42: 0x16104d3191b8 
43: 0x1e306abcabc0 
44: 0x1011f84f4 Builtins_InterpreterEntryTrampoline [/opt/homebrew/bin/node]
45: 0x161049ae2ff0 
46: 0x16104e8923a4 
47: 0x16104d3191b8 
48: 0x1e306abcabc0 
49: 0x1011f84f4 Builtins_InterpreterEntryTrampoline [/opt/homebrew/bin/node]
50: 0x161049ae2ff0 
51: 0x16104e1c81dc 
52: 0x16104d3192a4 
53: 0x1e306abcadd0 
54: 0x1011f84f4 Builtins_InterpreterEntryTrampoline [/opt/homebrew/bin/node]
55: 0x161049ae2dbc 
56: 0x16104e939bfc 
57: 0x16104d3192a4 
58: 0x1e306abcadd0 
59: 0x1011f84f4 Builtins_InterpreterEntryTrampoline [/opt/homebrew/bin/node]
60: 0x161049ae2dbc 
61: 0x16104e79afc0 
62: 0x16104d3193a4 
63: 0x1e306abcb060 
64: 0x1011f84f4 Builtins_InterpreterEntryTrampoline [/opt/homebrew/bin/node]
65: 0x161049ae2b9c 
66: 0x16104e6f37e0 
67: 0x16104d3192a4 
68: 0x1e306abcadd0 
69: 0x1011f84f4 Builtins_InterpreterEntryTrampoline [/opt/homebrew/bin/node]
70: 0x161049ae2dbc 
71: 0x16104e7359d0 
72: 0x16104d3191b8 
73: 0x1e306abcabc0 
74: 0x1011f84f4 Builtins_InterpreterEntryTrampoline [/opt/homebrew/bin/node]
75: 0x161049ae2ff0 
76: 0x16104e8923a4 
77: 0x16104d3191b8 
78: 0x1e306abcabc0 
79: 0x1011f84f4 Builtins_InterpreterEntryTrampoline [/opt/homebrew/bin/node]
80: 0x161049ae2ff0 
81: 0x16104e1c81dc 
82: 0x16104d3192a4 
83: 0x1e306abcadd0 
84: 0x1011f84f4 Builtins_InterpreterEntryTrampoline [/opt/homebrew/bin/node]
85: 0x161049ae2dbc 
86: 0x16104e939bfc 
87: 0x16104d3192a4 
88: 0x1e306abcadd0 
89: 0x1011f84f4 Builtins_InterpreterEntryTrampoline [/opt/homebrew/bin/node]
90: 0x161049ae2dbc 
91: 0x16104e79afc0 
92: 0x16104d3193a4 
93: 0x1e306abcb060 
94: 0x1011f84f4 Builtins_InterpreterEntryTrampoline [/opt/homebrew/bin/node]
95: 0x161049ae2b9c 
96: 0x16104e6f37e0 
97: 0x16104d3192a4 
98: 0x1e306abcadd0 
99: 0x1011f84f4 Builtins_InterpreterEntryTrampoline [/opt/homebrew/bin/node]
100: 0x161049ae2dbc 
101: 0x16104e865184 
102: 0x16104d3193a4 
103: 0x1e306abcb060 
104: 0x1011f84f4 Builtins_InterpreterEntryTrampoline [/opt/homebrew/bin/node]
105: 0x161049ae2b9c 
106: 0x16104e1465dc 
107: 0x16104d3192a4 
108: 0x1e306abcadd0 
109: 0x1011f84f4 Builtins_InterpreterEntryTrampoline [/opt/homebrew/bin/node]
110: 0x161049ae2dbc 
111: 0x16104ac48b1c 
112: 0x16104d3191b8 
113: 0x1e306abcabc0 
114: 0x1011f84f4 Builtins_InterpreterEntryTrampoline [/opt/homebrew/bin/node]
115: 0x161049ae2ff0 
116: 0x16104e6c6290 
117: 0x16104d3192a4 
118: 0x1e306abcadd0 
119: 0x1011f84f4 Builtins_InterpreterEntryTrampoline [/opt/homebrew/bin/node]
120: 0x161049ae2dbc 
121: 0x1610499b93b0 
122: 0x16104d3192a4 
123: 0x1e306abcadd0 
124: 0x1011f84f4 Builtins_InterpreterEntryTrampoline [/opt/homebrew/bin/node]
125: 0x161049ae2dbc 
126: 0x16104cf883dc 
127: 0x16104d3191b8 
128: 0x1e306abcabc0 
129: 0x1011f84f4 Builtins_InterpreterEntryTrampoline [/opt/homebrew/bin/node]
130: 0x161049ae2ff0 
131: 0x16104ac4d8e4 
132: 0x16104d3192a4 
133: 0x1e306abcadd0 
134: 0x1011f84f4 Builtins_InterpreterEntryTrampoline [/opt/homebrew/bin/node]
135: 0x161049ae2dbc 
136: 0x16104e35c854 
137: 0x16104c7be008 
138: 0x16104d31c7b8 
139: 0x1e306abca618 
140: 0x1011f84f4 Builtins_InterpreterEntryTrampoline [/opt/homebrew/bin/node]
141: 0x161049ae3180 
142: 0x16104f36252c 
143: 0x16104d3192a4 
144: 0x1e306abcadd0 
145: 0x1011f84f4 Builtins_InterpreterEntryTrampoline [/opt/homebrew/bin/node]
146: 0x161049ae2dbc 
147: 0x16104e515998 
148: 0x16104e51e2ac 
149: 0x161049c8609c 
150: 0x1e306abca618 
151: 0x1011f84f4 Builtins_InterpreterEntryTrampoline [/opt/homebrew/bin/node]
152: 0x1011f84f4 Builtins_InterpreterEntryTrampoline [/opt/homebrew/bin/node]
153: 0x1011efb24 Builtins_ArgumentsAdaptorTrampoline [/opt/homebrew/bin/node]
154: 0x1011f84f4 Builtins_InterpreterEntryTrampoline [/opt/homebrew/bin/node]
155: 0x1011f84f4 Builtins_InterpreterEntryTrampoline [/opt/homebrew/bin/node]
156: 0x1011f84f4 Builtins_InterpreterEntryTrampoline [/opt/homebrew/bin/node]
157: 0x1011efb24 Builtins_ArgumentsAdaptorTrampoline [/opt/homebrew/bin/node]
158: 0x1011f84f4 Builtins_InterpreterEntryTrampoline [/opt/homebrew/bin/node]
159: 0x1011f84f4 Builtins_InterpreterEntryTrampoline [/opt/homebrew/bin/node]
160: 0x1011f84f4 Builtins_InterpreterEntryTrampoline [/opt/homebrew/bin/node]
161: 0x101226dbc Builtins_GeneratorPrototypeNext [/opt/homebrew/bin/node]
162: 0x1011f84f4 Builtins_InterpreterEntryTrampoline [/opt/homebrew/bin/node]
163: 0x1012a9b44 Builtins_PromiseConstructor [/opt/homebrew/bin/node]
164: 0x1011f510c Builtins_JSBuiltinsConstructStub [/opt/homebrew/bin/node]
165: 0x1012e9d74 Builtins_ConstructHandler [/opt/homebrew/bin/node]
166: 0x1011f84f4 Builtins_InterpreterEntryTrampoline [/opt/homebrew/bin/node]
167: 0x1011f84f4 Builtins_InterpreterEntryTrampoline [/opt/homebrew/bin/node]
168: 0x1011f84f4 Builtins_InterpreterEntryTrampoline [/opt/homebrew/bin/node]
169: 0x101226dbc Builtins_GeneratorPrototypeNext [/opt/homebrew/bin/node]
170: 0x1011f84f4 Builtins_InterpreterEntryTrampoline [/opt/homebrew/bin/node]
171: 0x1012aba7c Builtins_PromiseFulfillReactionJob [/opt/homebrew/bin/node]
172: 0x101217668 Builtins_RunMicrotasks [/opt/homebrew/bin/node]
173: 0x1011f5c88 Builtins_JSRunMicrotasksEntry [/opt/homebrew/bin/node]
174: 0x148008000 
[1]    39755 trace trap  truffle compile


```

## Environment

* Operating System: Big Sur 11.2.1 (20D74)
* Ethereum client: geth 1.9.25
* Truffle version (`truffle version`): 5.1.65/5.1.66
* node version (`node --version`): 15.7.0
* npm version (`npm --version`): 7.4.3

**Comment by UnsignedInt8** [comment]
Fixed at 5.2.0

**Comment by mintotsai** [comment]
Hi, I seem to still be running into the same issue on v5.2.0. I may be missing a step.

```
% truffle version

Truffle v5.2.0 (core: 5.2.0)
Solidity - >=0.6.0 <0.8.0 (solc-js)
Node v15.8.0
Web3.js v1.2.9
```

```
% truffle compile


Compiling your contracts...
===========================
✔ Fetching solc version list from solc-bin. Attempt #1
> Compiling ./contracts/Token.sol
⠼ Fetching solc version list from solc-bin. Attempt #1

#
# Fatal error in , line 0
# Check failed: allocator->SetPermissions(reinterpret_cast<void*>(region.begin()), region.size(), PageAllocator::kNoAccess).
#
#
#
#FailureMessage Object: 0x16dc927c8
 1: 0x10225d104 node::NodePlatform::GetStackTracePrinter()::$_3::__invoke() [/opt/homebrew/bin/node]
 2: 0x102be8054 V8_Fatal(char const*, ...) [/opt/homebrew/bin/node]
 3: 0x1027d1358 v8::internal::wasm::WasmCodeAllocator::GetNumCodeSpaces() const [/opt/homebrew/bin/node]
 4: 0x1027d11f8 v8::internal::wasm::WasmCodeAllocator::FreeCode(v8::internal::Vector<v8::internal::wasm::WasmCode* const>) [/opt/homebrew/bin/node]
 5: 0x1027d4048 v8::internal::wasm::NativeModule::FreeCode(v8::internal::Vector<v8::internal::wasm::WasmCode* const>) [/opt/homebrew/bin/node]
 6: 0x1027e1bcc v8::internal::wasm::WasmEngine::FreeDeadCodeLocked(std::__1::unordered_map<v8::internal::wasm::NativeModule*, std::__1::vector<v8::internal::wasm::WasmCode*, std::__1::allocator<v8::internal::wasm::WasmCode*> >, std::__1::hash<v8::internal::wasm::NativeModule*>, std::__1::equal_to<v8::internal::wasm::NativeModule*>, std::__1::allocator<std::__1::pair<v8::internal::wasm::NativeModule* const, std::__1::vector<v8::internal::wasm::WasmCode*, std::__1::allocator<v8::internal::wasm::WasmCode*> > > > > const&) [/opt/homebrew/bin/node]
 7: 0x1027dfbec v8::internal::wasm::WasmEngine::PotentiallyFinishCurrentGC() [/opt/homebrew/bin/node]
 8: 0x1027e0e28 v8::internal::wasm::WasmEngine::ReportLiveCodeForGC(v8::internal::Isolate*, v8::internal::Vector<v8::internal::wasm::WasmCode*>) [/opt/homebrew/bin/node]
 9: 0x1027e3548 v8::internal::wasm::(anonymous namespace)::WasmGCForegroundTask::RunInternal() [/opt/homebrew/bin/node]
10: 0x10225bbc0 node::PerIsolatePlatformData::RunForegroundTask(std::__1::unique_ptr<v8::Task, std::__1::default_delete<v8::Task> >) [/opt/homebrew/bin/node]
11: 0x10225acb4 node::PerIsolatePlatformData::FlushForegroundTasksInternal() [/opt/homebrew/bin/node]
12: 0x1028d61a4 uv__async_io [/opt/homebrew/bin/node]
13: 0x1028e5d18 uv__io_poll [/opt/homebrew/bin/node]
14: 0x1028d65c4 uv_run [/opt/homebrew/bin/node]
15: 0x102168a88 node::SpinEventLoop(node::Environment*) [/opt/homebrew/bin/node]
16: 0x102239224 node::NodeMainInstance::Run(node::EnvSerializeInfo const*) [/opt/homebrew/bin/node]
17: 0x1021dcce4 node::Start(int, char**) [/opt/homebrew/bin/node]
18: 0x19a4f5f34 start [/usr/lib/system/libdyld.dylib]
^Czsh: killed     truffle compile
```

**Comment by UnsignedInt8** [comment]
> Hi, I seem to still be running into the same issue on v5.2.0. I may be missing a step.
> 
> ```
> % truffle version
> 
> Truffle v5.2.0 (core: 5.2.0)
> Solidity - >=0.6.0 <0.8.0 (solc-js)
> Node v15.8.0
> Web3.js v1.2.9
> ```
> 
> ```
> % truffle compile
> 
> 
> Compiling your contracts...
> ===========================
> ✔ Fetching solc version list from solc-bin. Attempt #1
> > Compiling ./contracts/Token.sol
> ⠼ Fetching solc version list from solc-bin. Attempt #1
> 
> #
> # Fatal error in , line 0
> # Check failed: allocator->SetPermissions(reinterpret_cast<void*>(region.begin()), region.size(), PageAllocator::kNoAccess).
> #
> #
> #
> #FailureMessage Object: 0x16dc927c8
>  1: 0x10225d104 node::NodePlatform::GetStackTracePrinter()::$_3::__invoke() [/opt/homebrew/bin/node]
>  2: 0x102be8054 V8_Fatal(char const*, ...) [/opt/homebrew/bin/node]
>  3: 0x1027d1358 v8::internal::wasm::WasmCodeAllocator::GetNumCodeSpaces() const [/opt/homebrew/bin/node]
>  4: 0x1027d11f8 v8::internal::wasm::WasmCodeAllocator::FreeCode(v8::internal::Vector<v8::internal::wasm::WasmCode* const>) [/opt/homebrew/bin/node]
>  5: 0x1027d4048 v8::internal::wasm::NativeModule::FreeCode(v8::internal::Vector<v8::internal::wasm::WasmCode* const>) [/opt/homebrew/bin/node]
>  6: 0x1027e1bcc v8::internal::wasm::WasmEngine::FreeDeadCodeLocked(std::__1::unordered_map<v8::internal::wasm::NativeModule*, std::__1::vector<v8::internal::wasm::WasmCode*, std::__1::allocator<v8::internal::wasm::WasmCode*> >, std::__1::hash<v8::internal::wasm::NativeModule*>, std::__1::equal_to<v8::internal::wasm::NativeModule*>, std::__1::allocator<std::__1::pair<v8::internal::wasm::NativeModule* const, std::__1::vector<v8::internal::wasm::WasmCode*, std::__1::allocator<v8::internal::wasm::WasmCode*> > > > > const&) [/opt/homebrew/bin/node]
>  7: 0x1027dfbec v8::internal::wasm::WasmEngine::PotentiallyFinishCurrentGC() [/opt/homebrew/bin/node]
>  8: 0x1027e0e28 v8::internal::wasm::WasmEngine::ReportLiveCodeForGC(v8::internal::Isolate*, v8::internal::Vector<v8::internal::wasm::WasmCode*>) [/opt/homebrew/bin/node]
>  9: 0x1027e3548 v8::internal::wasm::(anonymous namespace)::WasmGCForegroundTask::RunInternal() [/opt/homebrew/bin/node]
> 10: 0x10225bbc0 node::PerIsolatePlatformData::RunForegroundTask(std::__1::unique_ptr<v8::Task, std::__1::default_delete<v8::Task> >) [/opt/homebrew/bin/node]
> 11: 0x10225acb4 node::PerIsolatePlatformData::FlushForegroundTasksInternal() [/opt/homebrew/bin/node]
> 12: 0x1028d61a4 uv__async_io [/opt/homebrew/bin/node]
> 13: 0x1028e5d18 uv__io_poll [/opt/homebrew/bin/node]
> 14: 0x1028d65c4 uv_run [/opt/homebrew/bin/node]
> 15: 0x102168a88 node::SpinEventLoop(node::Environment*) [/opt/homebrew/bin/node]
> 16: 0x102239224 node::NodeMainInstance::Run(node::EnvSerializeInfo const*) [/opt/homebrew/bin/node]
> 17: 0x1021dcce4 node::Start(int, char**) [/opt/homebrew/bin/node]
> 18: 0x19a4f5f34 start [/usr/lib/system/libdyld.dylib]
> ^Czsh: killed     truffle compile
> ```

you can update node to 15.9.0

**Comment by gnidan** [comment]
Sounds like this is still an issue, since Truffle shouldn't require Node v15!

**Comment by eshaben** [comment]
@UnsignedInt8 thanks for reporting the issue and we'll look into this!

**Comment by oishun1112** [comment]
I got the same one and was fixed by updating to v5.2.3

**Comment by eggplantzzz** [comment]
Can anyone here verify that this is/isn't an issue on the latest Truffle (currently 5.4.3)? I'm trying to see if this is still an issue for some people as I cannot reproduce it. If it is still an issue and you have reproduction steps that consistently cause this that would be super helpful!

**Comment by haltman-at** [comment]
Closing this for issue maintenance.
